### PR TITLE
Migrated to null safety and made another branch

### PR DESCRIPTION
**Pull request by IsmailAlamKhan**

### CODE REVIEW

**Comment by MarceloRab** [comment]
My suggestions in graphx_widget.dart - > SceneBuilderWidget

` final SceneController Function() builder;`
...
`required this.builder,`
...

`late SceneController _controller;`

...

`_controller = widget.builder();`
'

**Comment by MarceloRab** [comment]
Excuse me. I still don't know how to pull.

**Comment by MarceloRab** [comment]
My suggestions in render.dart - > graphics

final points = List<Offset>.filled(sides, null);   = >     final points = List<Offset>.filled(sides, Offset(0, 0));

**NOTICE**: This constructor cannot be used in null-safe code.
  /// Use [List.filled] to create a non-empty list.

**Comment by IsmailAlamKhan** [comment]
@MarceloRab I fixed what you suggested.

**Comment by MarceloRab** [comment]
FIx - core > scene_controller

f ((_config.useKeyboard ?? false) || (_config.usePointer ?? false)) {


I don't know why it is generating an error. Would it be something on nullsafety?

**Comment by IsmailAlamKhan** [comment]
> 
> 
> FIx - core > scene_controller
> 
> f ((_config.useKeyboard ?? false) || (_config.usePointer ?? false)) {
> 
> I don't know why it is generating an error. Would it be something on nullsafety?
Can you say what error you are getting?

**Pull request closed without merging**
